// Code generated by solo-kit. DO NOT EDIT.

package v1

import (
	"github.com/solo-io/solo-kit/pkg/api/v1/clients"
	"github.com/solo-io/solo-kit/pkg/api/v1/reconcile"
	"github.com/solo-io/solo-kit/pkg/api/v1/resources"
	"github.com/solo-io/solo-kit/pkg/utils/contextutils"
)

// Option to copy anything from the original to the desired before writing. Return value of false means don't update
type TransitionClusterScopedResourceFunc func(original, desired *ClusterScopedResource) (bool, error)

type ClusterScopedResourceReconciler interface {
	Reconcile(namespace string, desiredResources ClusterScopedResourceList, transition TransitionClusterScopedResourceFunc, opts clients.ListOpts) error
}

func clusterScopedResourcesToResources(list ClusterScopedResourceList) resources.ResourceList {
	var resourceList resources.ResourceList
	for _, clusterScopedResource := range list {
		resourceList = append(resourceList, clusterScopedResource)
	}
	return resourceList
}

func NewClusterScopedResourceReconciler(client ClusterScopedResourceClient) ClusterScopedResourceReconciler {
	return &clusterScopedResourceReconciler{
		base: reconcile.NewReconciler(client.BaseClient()),
	}
}

type clusterScopedResourceReconciler struct {
	base reconcile.Reconciler
}

func (r *clusterScopedResourceReconciler) Reconcile(namespace string, desiredResources ClusterScopedResourceList, transition TransitionClusterScopedResourceFunc, opts clients.ListOpts) error {
	opts = opts.WithDefaults()
	opts.Ctx = contextutils.WithLogger(opts.Ctx, "clusterScopedResource_reconciler")
	var transitionResources reconcile.TransitionResourcesFunc
	if transition != nil {
		transitionResources = func(original, desired resources.Resource) (bool, error) {
			return transition(original.(*ClusterScopedResource), desired.(*ClusterScopedResource))
		}
	}
	return r.base.Reconcile(namespace, clusterScopedResourcesToResources(desiredResources), transitionResources, opts)
}
