// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/solo-io/solo-kit/test/mocks/api/v1/more_mock_resources.proto

package v1 // import "github.com/solo-io/solo-kit/test/mocks/v1"

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import core "github.com/solo-io/solo-kit/pkg/api/v1/resources/core"

import bytes "bytes"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

//
// Description of the AnotherMockResource
type AnotherMockResource struct {
	Metadata core.Metadata `protobuf:"bytes,1,opt,name=metadata" json:"metadata"`
	Status   core.Status   `protobuf:"bytes,6,opt,name=status" json:"status"`
	// comments that go above the basic field in our docs
	BasicField           string   `protobuf:"bytes,2,opt,name=basic_field,json=basicField,proto3" json:"basic_field,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnotherMockResource) Reset()         { *m = AnotherMockResource{} }
func (m *AnotherMockResource) String() string { return proto.CompactTextString(m) }
func (*AnotherMockResource) ProtoMessage()    {}
func (*AnotherMockResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_more_mock_resources_296e1b2e99c78a4b, []int{0}
}
func (m *AnotherMockResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnotherMockResource.Unmarshal(m, b)
}
func (m *AnotherMockResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnotherMockResource.Marshal(b, m, deterministic)
}
func (dst *AnotherMockResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnotherMockResource.Merge(dst, src)
}
func (m *AnotherMockResource) XXX_Size() int {
	return xxx_messageInfo_AnotherMockResource.Size(m)
}
func (m *AnotherMockResource) XXX_DiscardUnknown() {
	xxx_messageInfo_AnotherMockResource.DiscardUnknown(m)
}

var xxx_messageInfo_AnotherMockResource proto.InternalMessageInfo

func (m *AnotherMockResource) GetMetadata() core.Metadata {
	if m != nil {
		return m.Metadata
	}
	return core.Metadata{}
}

func (m *AnotherMockResource) GetStatus() core.Status {
	if m != nil {
		return m.Status
	}
	return core.Status{}
}

func (m *AnotherMockResource) GetBasicField() string {
	if m != nil {
		return m.BasicField
	}
	return ""
}

//
// ClusterScopedResource tests Cluster-Level Scoping of CRDs
type ClusterScopedResource struct {
	Metadata core.Metadata `protobuf:"bytes,1,opt,name=metadata" json:"metadata"`
	Status   core.Status   `protobuf:"bytes,6,opt,name=status" json:"status"`
	// arbitrary data for testing
	BasicField           string   `protobuf:"bytes,2,opt,name=basic_field,json=basicField,proto3" json:"basic_field,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterScopedResource) Reset()         { *m = ClusterScopedResource{} }
func (m *ClusterScopedResource) String() string { return proto.CompactTextString(m) }
func (*ClusterScopedResource) ProtoMessage()    {}
func (*ClusterScopedResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_more_mock_resources_296e1b2e99c78a4b, []int{1}
}
func (m *ClusterScopedResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterScopedResource.Unmarshal(m, b)
}
func (m *ClusterScopedResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterScopedResource.Marshal(b, m, deterministic)
}
func (dst *ClusterScopedResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterScopedResource.Merge(dst, src)
}
func (m *ClusterScopedResource) XXX_Size() int {
	return xxx_messageInfo_ClusterScopedResource.Size(m)
}
func (m *ClusterScopedResource) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterScopedResource.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterScopedResource proto.InternalMessageInfo

func (m *ClusterScopedResource) GetMetadata() core.Metadata {
	if m != nil {
		return m.Metadata
	}
	return core.Metadata{}
}

func (m *ClusterScopedResource) GetStatus() core.Status {
	if m != nil {
		return m.Status
	}
	return core.Status{}
}

func (m *ClusterScopedResource) GetBasicField() string {
	if m != nil {
		return m.BasicField
	}
	return ""
}

func init() {
	proto.RegisterType((*AnotherMockResource)(nil), "testing.solo.io.AnotherMockResource")
	proto.RegisterType((*ClusterScopedResource)(nil), "testing.solo.io.ClusterScopedResource")
}
func (this *AnotherMockResource) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*AnotherMockResource)
	if !ok {
		that2, ok := that.(AnotherMockResource)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Metadata.Equal(&that1.Metadata) {
		return false
	}
	if !this.Status.Equal(&that1.Status) {
		return false
	}
	if this.BasicField != that1.BasicField {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *ClusterScopedResource) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ClusterScopedResource)
	if !ok {
		that2, ok := that.(ClusterScopedResource)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Metadata.Equal(&that1.Metadata) {
		return false
	}
	if !this.Status.Equal(&that1.Status) {
		return false
	}
	if this.BasicField != that1.BasicField {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}

func init() {
	proto.RegisterFile("github.com/solo-io/solo-kit/test/mocks/api/v1/more_mock_resources.proto", fileDescriptor_more_mock_resources_296e1b2e99c78a4b)
}

var fileDescriptor_more_mock_resources_296e1b2e99c78a4b = []byte{
	// 340 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x92, 0x41, 0x4e, 0x3a, 0x31,
	0x14, 0xc6, 0x29, 0xff, 0xf9, 0xa3, 0x3e, 0x16, 0x26, 0x23, 0xe2, 0xc8, 0x42, 0x08, 0x2b, 0x5c,
	0x38, 0x15, 0xdc, 0x18, 0x77, 0x62, 0xa2, 0x2b, 0x36, 0xb0, 0x73, 0x43, 0x4a, 0xa9, 0x43, 0x03,
	0xc3, 0x23, 0x6d, 0x87, 0x03, 0x70, 0x1a, 0x8f, 0xe2, 0x05, 0x4c, 0x5c, 0xb9, 0xf0, 0x06, 0x73,
	0x03, 0xd3, 0x99, 0x0e, 0x89, 0x89, 0x31, 0xb8, 0x73, 0xd5, 0xf6, 0xbd, 0xef, 0x97, 0xf7, 0x7d,
	0x79, 0x85, 0x87, 0x48, 0x9a, 0x59, 0x32, 0x09, 0x39, 0xc6, 0x54, 0xe3, 0x02, 0x2f, 0x24, 0xe6,
	0xe7, 0x5c, 0x1a, 0x6a, 0x84, 0x36, 0x34, 0x46, 0x3e, 0xd7, 0x94, 0xad, 0x24, 0x5d, 0x77, 0x69,
	0x8c, 0x4a, 0x8c, 0x6d, 0x65, 0xac, 0x84, 0xc6, 0x44, 0x71, 0xa1, 0xc3, 0x95, 0x42, 0x83, 0xfe,
	0xa1, 0x15, 0xcb, 0x65, 0x14, 0x5a, 0x3a, 0x94, 0xd8, 0xa8, 0x45, 0x18, 0x61, 0xd6, 0xa3, 0xf6,
	0x96, 0xcb, 0x1a, 0xdd, 0x9f, 0xe6, 0x15, 0x43, 0x84, 0x61, 0x53, 0x66, 0x98, 0x43, 0xe8, 0x0e,
	0x88, 0x36, 0xcc, 0x24, 0xfa, 0x17, 0x33, 0x8a, 0x77, 0x8e, 0xb4, 0x5f, 0x09, 0x1c, 0xdd, 0x2e,
	0xd1, 0xcc, 0x84, 0x1a, 0x20, 0x9f, 0x0f, 0x5d, 0x38, 0xff, 0x1a, 0xf6, 0x0b, 0x37, 0x01, 0x69,
	0x91, 0x4e, 0xb5, 0x57, 0x0f, 0x39, 0x2a, 0x51, 0xa4, 0x0c, 0x07, 0xae, 0xdb, 0xf7, 0x5e, 0xde,
	0x9b, 0xa5, 0xe1, 0x56, 0xed, 0xf7, 0xa0, 0x92, 0x9b, 0x0a, 0x2a, 0x19, 0x57, 0xfb, 0xca, 0x8d,
	0xb2, 0x9e, 0xa3, 0x9c, 0xd2, 0x6f, 0x42, 0x75, 0xc2, 0xb4, 0xe4, 0xe3, 0x27, 0x29, 0x16, 0xd3,
	0xa0, 0xdc, 0x22, 0x9d, 0x83, 0x21, 0x64, 0xa5, 0x7b, 0x5b, 0xb9, 0xa1, 0x9b, 0xd4, 0xdb, 0x83,
	0xff, 0xf0, 0x8f, 0xc5, 0x6a, 0x93, 0x7a, 0x01, 0xd4, 0xfd, 0x1a, 0xcb, 0x6d, 0xdb, 0xa5, 0x6c,
	0x77, 0xb2, 0x49, 0x3d, 0x0f, 0xca, 0xad, 0x52, 0xfb, 0x8d, 0xc0, 0xf1, 0xdd, 0x22, 0xd1, 0x46,
	0xa8, 0x11, 0xc7, 0x95, 0x98, 0xfe, 0xd5, 0x64, 0x97, 0x45, 0x32, 0xae, 0x6d, 0xb2, 0x53, 0x38,
	0xf1, 0xbf, 0x37, 0xee, 0xa2, 0x91, 0x3e, 0x7d, 0xfe, 0x38, 0x23, 0x8f, 0xe7, 0x3b, 0xfe, 0xdf,
	0x75, 0x77, 0x52, 0xc9, 0x56, 0x7d, 0xf5, 0x19, 0x00, 0x00, 0xff, 0xff, 0x7e, 0x7e, 0xa8, 0xf1,
	0xf3, 0x02, 0x00, 0x00,
}
